### ISSUE TITLE
Quiz description, question text and answer text not showing

### ISSUE THREAD

**Issue by thespianuk** [joomplace/joomla-quiz#2]
Using Joomla 3.10.9, PHP7.4,  Helix 3 template.  Short description shows in category view.  Description text doesn't show when selecting a quiz.  Example multi reposes question doesn't show question text or answer text.  Example true and false question doesn't show question text but shows "true or false" before options.

Have tested with J Default Protostar template and same behaviour.  Real shame as extension looks really neat.

Tested on a 3.9.18 install (same php version) with the same template framework and the above text shows up.

Access log error line from failing install:
[Wed Jan 18 16:20:39.853021 2023] [php7:notice] [pid 20032:tid 139797955798784] [client 172.16.1.191:63580] PHP Notice:  Undefined offset: 0 in /var/www/wecare/components/com_joomlaquiz/models/ajaxaction.php on line 209, referer: https://newt.smhsct.local/wecare-test/take-a-quiz

Tested further on same J3.10.9 build on a php 8 server.  Same issue so must be a 3.10.x problem.

sem

**Comment by fsvblr** [comment]
Hi Sem,
Unable to reproduce the reported issues.
Please submit a request at https://joomplace.com/contact.html and we’ll be happy to help.

**Comment by thespianuk** [comment]
Hi - just went through enabled plugins disabling and testing - initially had ECR (Easy Content Restriction) on site to provide an initial password to unlock content.  Had turned the password feature off but plugin was still enabled.  Disabling this made everything work.  It's a really neat component - please get it J4 ready and keep developing it.  Thanks, sem
